# Python Review 

Goals: 
- recall basic python vocabulary 
- practice markdown 

## Libraries and packages

**library** collection of code that we can use to perform specific tasks in our programs. 

**NumPy** 

- core library for computing in python 
- many other libraries use NumPy as building blocks 
- computations on NumPy are optimized for speed and memory usage 

Let's import NumPy with standard abbreviation **np**

In [1]:
import numpy as np 

## Variables 

**variable** : name we assign to a particular object in Python

Example: 

In [2]:
# Assign a small array to a variable a 

a = np.array([[1,1,2],[3,5,8]]) 

In [3]:
# Run cell with variable name to show value 
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use print function to print the value 
print(a)

[[1 1 2]
 [3 5 8]]


## Objects 
**object** (informally speaking) a bundle of properties and actions about something specific. 

Example: 

Object: dataframe 

Properties: number of rows, names of columns, date created

Actions: selecting a specific row, adding a new column 

A variable is the same name we give a specific object, and the same object van be referenced by different variables. 

In practice we can often use variable and object interchangeably. 

### Types 

Every object in Python has a type, the type tells us which kind of object it is. Type and class are interchangeable. 

We can see the type/class of a variable/object by uisng the **type** function.

In [5]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The **numpy.ndarray** is the core object/data type in the NumPy package. We can check the type of an entry in the array by indexing: 

In [17]:
print(a[0,0])

# Check the type on an entry on the array by indexing 
type(a[0,0])

1


numpy.int64

Notice that `type(a[0,0])` is **numpy.int64** tells us the 1 is stored as a 64-bit number. NumPy has its own data types to deal with numbers depending on memory storage and floating point precision. 

Access value 5 in the array: 

In [7]:
print(a[1,1])

5


### Functions 

print was our first example of a Python **function**. Functions take in a set of arguments, separated by commas and use those arguments to create an **output**. 

There are several built-in functions in Python, most of them are for interacting with the Python basic data types such as `int` (integers), `float` (decimal numbers), `str` (strings), and `bool` (boolean values). 

Argument and parameter will be used interchangeably. 

**parameter** is a variable in the function definition that accepts an argument passed to the function. It is a placeholder in the function that will receive the value of an argument when the function is caled. 

In [8]:
def my_function(parameter1, parameter2):
    return parameter1 + parameter2

`parameter1` and `paramter2` are paramters. When we call the function

In [9]:
result = my_function(5,10)
result

15

We have the 5 and 10 are arguments passed into the function. 

We'll see paramter more often in a package's documentation. 

### Documentation 

We can ask for information about what a function does by executing `?` followed by the function name. 

In [10]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

We obtain **docstring**, a special type of comment that is used to document how a function(or class, or module) works. 

The first line tells us the function name followed by arguments in parentheses. 

**non-optional arguments**: arguments you need to specify for the function to do something

**optional arguments**: arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis() in form `opt_arg = `def_val`

In [18]:
print('changing the end of an argument', end = ':)')

changing the end of an argument:)

### Attributes and methods 

An object in Python has attributes and methods. 

An **attribute** is a property of the object, some piece of information about it. 

A **method** is a function associated with an object, so it is an action where the main ingredient is the object 


We can access a variable's attributes and methods by adding a period `.` at the end of the variable's name. So we would write: 

`variable.variable_method()` or `variable.variable_attribute()`

Check in 

fish attributes
-length, color, species 

Fish methods
- die(), bite(), swim()


NumPy arrays have many methods and attributes 

In [19]:
# Methods examples 

# min returns the minimum value of a specified axis 
a.min(axis =0)

array([1, 1, 2])

In [11]:
# A 3x3 array
var = np.array([[1,2,3],[4,5,6],[7,8,9]])
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`T` is an example of attribute, it returns the transpose of `var`:

In [12]:
print(var.T)
print(type(var.T))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
<class 'numpy.ndarray'>


`shape` is another attribute, tells us the shape of the array.

In [13]:
print(var.shape)
print(type(var.shape))

(3, 3)
<class 'tuple'>


The `tolist` method returns the minimum value in the array along a specified axis:

In [14]:
var.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
var.min()

1

In [16]:
var.min(axis = 0)

array([1, 2, 3])

## Excercise 

1. Read the `print` function help. What is the **type** of the argument `sep`? 

2. Create two new variables, one with integer value 77 and another with the string 99. 

3. Use your variables to print `77%99%77` by changing the value of one of the optional arguments in `print`.

In [20]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

1. The argument `sep` is an optional argument 

In [27]:
a = 77 
b = '99'

In [29]:
print(a,b,a, sep = '%')

77%99%77
