# Python Review 

Goals: 
- recall basic python vocabulary 
- practice markdown 

## Libraries and packages

**library** collection of code that we can use to perform specific tasks in our programs. 

**NumPy** 

- core library for computing in python 
- many other libraries use NumPy as building blocks 
- computations on NumPy are optimized for speed and memory usage 

Let's import NumPy with standard abbreviation**

In [1]:
import numpy as np 

## Variables 

**variable** name we assign to a particular object in Python

Example: 

In [2]:
# Assign a small array to a variable a 

a = np.array([[1,1,2],[3,5,8]]) 

In [3]:
# Run cell with variable name to show value 
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use print function to print the value 
print(a)

[[1 1 2]
 [3 5 8]]


## Objects 
**object** (informally speaking) a bundle of properties and actions about something specific. 

Example: 

Object: dataframe 

Properties: number of rows, names of columns, date created

Actions: selecting a specific row, adding a new column 

A variable is the same name we give a specific object, and the same object van be referenced by different variables. 

In practice we can often use variable and object interchangeably. 

-
